apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base

patches:
  - path: patches/replica-count.yaml
  - path: patches/resources.yaml

images:
  - name: ghcr.io/ericwang984/sre-demo-app
    newTag: v1.0.0
